# Generated by Django 5.2.12 on 2026-03-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_slide_remove_sliderimage_slider_delete_slider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Картинка Категории Продукта'),
        ),
    ]
