# Generated by Django 5.2.12 on 2026-03-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=0, max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
